#!/bin/bash

LUNA_ROOT="/opt/myLuna"

case "$1" in

create-client)
    $LUNA_ROOT/shared/scripts/create-client.sh "$2"
    ;;

delete-client)
    $LUNA_ROOT/shared/scripts/delete-client.sh "$2"
    ;;

list-clients)
    $LUNA_ROOT/shared/scripts/list-clients.sh
    ;;

health-check)
    $LUNA_ROOT/shared/scripts/health-check.sh
    ;;

secret-add)
    $LUNA_ROOT/shared/scripts/secret-add.sh "$2" "$3"
    ;;

secret-list)
    $LUNA_ROOT/shared/scripts/secret-list.sh "$2"
    ;;

secret-export)
    $LUNA_ROOT/shared/scripts/secret-export.sh "$2"
    ;;

backup)
    $LUNA_ROOT/shared/scripts/backup-client.sh "$2"
    ;;

restore)
    $LUNA_ROOT/shared/scripts/restore-client.sh "$2" "$3"
    ;;



*)
    echo ""
    echo "myLuna Commands"
    echo ""

    echo "Client:"
    echo "  myluna create-client NAME"
    echo "  myluna delete-client NAME"
    echo "  myluna list-clients"
    echo ""

    echo "Vault:"
    echo "  myluna secret-add CLIENT KEY"
    echo "  myluna secret-list CLIENT"
    echo "  myluna secret-export CLIENT"
    echo ""

    echo "Backup:"
    echo "  myluna backup CLIENT"
    echo "  myluna restore CLIENT BACKUP_FILE"
    echo ""

    echo "System:"
    echo "  myluna health-check"
    echo ""

    ;;
esac